package ml.mlazic.netqueue.queues;

import com.rabbitmq.client.Connection;

/**
 * Queue.java
 * Purpose: Main API interface.
 * @see ml.mlazic.netqueue.queues.BasicQueue
 *
 * @author Marko Lazic
 * @version 1.0 4/21/18
 */
public interface Queue {
    /**
     * Message is sent over an established link using transfer frame.
     * @param in an object to be sent.
     * @return returns object if it's sent.
     * returns -1 if exception occurs.
     */
    Object send(Object in);

    /**
     * Enstablish a link and receives the message, providing reliability
     * guarantees.
     * @return the consumerTag generated by the server. In case of exception returns -1.
     */
    Object receive();

    /** Opens the connection and begins the session. */
    void open();

    /** Ends the session and closes the connection. */
    void close();

    /** gets RabbitMQ connection handle. */
    Connection getConnection();
}
